"""Postgres-схема timechecker (E6, TIME-36) — зеркало SQLite-схемы.

Отличия от SQLite: ``id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY`` вместо autoincrement;
без ``PRAGMA``. Типы и ограничения совместимы (``INSERT … ON CONFLICT`` идентичен). ``meta_json``
остаётся TEXT (JSONB — возможная будущая оптимизация).
"""

from __future__ import annotations

_ID = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"

_V1 = f"""
CREATE TABLE employee (
  id               {_ID},
  windows_username TEXT NOT NULL UNIQUE,
  display_name     TEXT,
  dev_branch       TEXT,
  active           INTEGER NOT NULL DEFAULT 1,
  created_at       TEXT NOT NULL
);
CREATE TABLE project (
  id                 {_ID},
  slug               TEXT NOT NULL UNIQUE,
  claude_project_key TEXT,
  repo               TEXT,
  plane_project_id   TEXT,
  plane_identifier   TEXT,
  created_at         TEXT NOT NULL
);
CREATE TABLE task (
  id               {_ID},
  project_id       INTEGER NOT NULL REFERENCES project(id),
  plane_issue_id   TEXT UNIQUE,
  plane_identifier TEXT UNIQUE,
  canon_task_id    TEXT,
  title            TEXT,
  estimate_h       REAL,
  status           TEXT,
  updated_at       TEXT
);
CREATE TABLE ingest_run (
  id          {_ID},
  employee_id INTEGER NOT NULL REFERENCES employee(id),
  started_at  TEXT NOT NULL,
  finished_at TEXT,
  window_from TEXT,
  window_to   TEXT,
  sources     TEXT,
  status      TEXT NOT NULL DEFAULT 'running',
  error       TEXT,
  counts_json TEXT
);
CREATE TABLE activity_event (
  id            {_ID},
  employee_id   INTEGER NOT NULL REFERENCES employee(id),
  project_id    INTEGER REFERENCES project(id),
  task_id       INTEGER REFERENCES task(id),
  source        TEXT NOT NULL,
  event_type    TEXT NOT NULL,
  ts_utc        TEXT NOT NULL,
  external_id   TEXT,
  meta_json     TEXT,
  ingest_run_id INTEGER REFERENCES ingest_run(id),
  UNIQUE(source, external_id)
);
CREATE INDEX ix_event_emp_ts  ON activity_event(employee_id, ts_utc);
CREATE INDEX ix_event_task_ts ON activity_event(task_id, ts_utc);
CREATE TABLE claude_session (
  id            {_ID},
  employee_id   INTEGER NOT NULL REFERENCES employee(id),
  project_id    INTEGER REFERENCES project(id),
  task_id       INTEGER REFERENCES task(id),
  session_uid   TEXT NOT NULL UNIQUE,
  started_at    TEXT,
  ended_at      TEXT,
  message_count INTEGER DEFAULT 0,
  tool_calls    INTEGER DEFAULT 0,
  tokens_in     INTEGER DEFAULT 0,
  tokens_out    INTEGER DEFAULT 0,
  updated_at    TEXT
);
CREATE INDEX ix_session_emp ON claude_session(employee_id, started_at);
CREATE TABLE git_commit (
  id          {_ID},
  employee_id INTEGER NOT NULL REFERENCES employee(id),
  project_id  INTEGER REFERENCES project(id),
  sha         TEXT NOT NULL UNIQUE,
  branch      TEXT,
  ts_utc      TEXT,
  author      TEXT,
  subject     TEXT,
  updated_at  TEXT
);
CREATE INDEX ix_commit_emp ON git_commit(employee_id, ts_utc);
CREATE TABLE commit_task (
  commit_id INTEGER NOT NULL REFERENCES git_commit(id),
  task_id   INTEGER NOT NULL REFERENCES task(id),
  PRIMARY KEY (commit_id, task_id)
);
CREATE TABLE plane_transition (
  id          {_ID},
  task_id     INTEGER NOT NULL REFERENCES task(id),
  from_state  TEXT,
  to_state    TEXT,
  ts_utc      TEXT,
  external_id TEXT UNIQUE
);
CREATE TABLE daily_summary (
  id                {_ID},
  employee_id       INTEGER NOT NULL REFERENCES employee(id),
  work_date         TEXT NOT NULL,
  span_start        TEXT,
  span_end          TEXT,
  active_minutes    INTEGER DEFAULT 0,
  gap_minutes       INTEGER DEFAULT 0,
  idle_ge30_count   INTEGER DEFAULT 0,
  idle_ge30_minutes INTEGER DEFAULT 0,
  tasks_count       INTEGER DEFAULT 0,
  switches          INTEGER DEFAULT 0,
  longest_focus_min INTEGER DEFAULT 0,
  claude_messages   INTEGER DEFAULT 0,
  claude_tokens     INTEGER DEFAULT 0,
  commits           INTEGER DEFAULT 0,
  hygiene_score     REAL,
  computed_at       TEXT,
  UNIQUE(employee_id, work_date)
);
CREATE TABLE daily_task_time (
  id              {_ID},
  employee_id     INTEGER NOT NULL REFERENCES employee(id),
  work_date       TEXT NOT NULL,
  task_id         INTEGER NOT NULL REFERENCES task(id),
  active_minutes  INTEGER DEFAULT 0,
  claude_messages INTEGER DEFAULT 0,
  claude_tokens   INTEGER DEFAULT 0,
  commits         INTEGER DEFAULT 0,
  est_h           REAL,
  computed_at     TEXT,
  UNIQUE(employee_id, work_date, task_id)
);
CREATE TABLE daily_idle (
  id          {_ID},
  employee_id INTEGER NOT NULL REFERENCES employee(id),
  work_date   TEXT NOT NULL,
  gap_start   TEXT NOT NULL,
  gap_end     TEXT NOT NULL,
  minutes     INTEGER NOT NULL,
  computed_at TEXT
);
CREATE INDEX ix_idle_emp_date ON daily_idle(employee_id, work_date);
"""

_V2 = """
ALTER TABLE claude_session ADD COLUMN cache_read INTEGER DEFAULT 0;
ALTER TABLE claude_session ADD COLUMN cache_creation INTEGER DEFAULT 0;
ALTER TABLE claude_session ADD COLUMN model TEXT;
ALTER TABLE daily_summary ADD COLUMN claude_cache_read INTEGER DEFAULT 0;
ALTER TABLE daily_summary ADD COLUMN claude_cache_creation INTEGER DEFAULT 0;
ALTER TABLE daily_summary ADD COLUMN claude_cost_usd REAL DEFAULT 0;
ALTER TABLE daily_summary ADD COLUMN models TEXT;
ALTER TABLE daily_task_time ADD COLUMN claude_cache_read INTEGER DEFAULT 0;
ALTER TABLE daily_task_time ADD COLUMN claude_cache_creation INTEGER DEFAULT 0;
ALTER TABLE daily_task_time ADD COLUMN claude_cost_usd REAL DEFAULT 0;
"""

# v3 (E8, codex_usage) — зеркало SQLite-v3 (см. schema.py). Отличия диалекта: IDENTITY-id,
# GREATEST вместо MAX(0,…); без BEGIN/COMMIT — _executescript Postgres атомарен (один commit).
# ВАЖНО: _executescript режет скрипт по «;» — внутри литералов «;» быть не должно.
_V3 = f"""
CREATE TABLE agent_session (
  id            {_ID},
  employee_id   INTEGER NOT NULL REFERENCES employee(id),
  project_id    INTEGER REFERENCES project(id),
  task_id       INTEGER REFERENCES task(id),
  source        TEXT NOT NULL DEFAULT 'claude',
  session_uid   TEXT NOT NULL,
  started_at    TEXT,
  ended_at      TEXT,
  message_count INTEGER DEFAULT 0,
  tool_calls    INTEGER DEFAULT 0,
  tokens_in     INTEGER DEFAULT 0,
  tokens_out    INTEGER DEFAULT 0,
  cache_read    INTEGER DEFAULT 0,
  cache_creation INTEGER DEFAULT 0,
  model         TEXT,
  updated_at    TEXT,
  UNIQUE(source, session_uid)
);
INSERT INTO agent_session (id, employee_id, project_id, task_id, source, session_uid,
  started_at, ended_at, message_count, tool_calls, tokens_in, tokens_out,
  cache_read, cache_creation, model, updated_at)
SELECT id, employee_id, project_id, task_id, 'claude', session_uid,
  started_at, ended_at, message_count, tool_calls, tokens_in, tokens_out,
  cache_read, cache_creation, model, updated_at
FROM claude_session;
DROP TABLE claude_session;
CREATE INDEX ix_agent_session_emp ON agent_session(employee_id, started_at);
SELECT setval(pg_get_serial_sequence('agent_session', 'id'),
  COALESCE((SELECT MAX(id) FROM agent_session), 1),
  (SELECT MAX(id) FROM agent_session) IS NOT NULL);
CREATE TABLE daily_agent_usage (
  id             {_ID},
  employee_id    INTEGER NOT NULL REFERENCES employee(id),
  work_date      TEXT    NOT NULL,
  task_id        INTEGER REFERENCES task(id),
  source         TEXT    NOT NULL DEFAULT 'claude',
  messages       INTEGER NOT NULL DEFAULT 0,
  tokens         INTEGER NOT NULL DEFAULT 0,
  cache_read     INTEGER NOT NULL DEFAULT 0,
  cache_creation INTEGER NOT NULL DEFAULT 0,
  cost_usd       REAL    NOT NULL DEFAULT 0,
  computed_at    TEXT
);
CREATE INDEX ix_agent_usage_emp_date ON daily_agent_usage(employee_id, work_date);
INSERT INTO daily_agent_usage (employee_id, work_date, task_id, source, messages, tokens,
  cache_read, cache_creation, cost_usd, computed_at)
SELECT employee_id, work_date, task_id, 'claude',
  COALESCE(claude_messages, 0), COALESCE(claude_tokens, 0),
  COALESCE(claude_cache_read, 0), COALESCE(claude_cache_creation, 0),
  COALESCE(claude_cost_usd, 0), computed_at
FROM daily_task_time
WHERE COALESCE(claude_messages, 0) + COALESCE(claude_tokens, 0)
      + COALESCE(claude_cost_usd, 0) > 0;
INSERT INTO daily_agent_usage (employee_id, work_date, task_id, source, messages, tokens,
  cache_read, cache_creation, cost_usd, computed_at)
SELECT s.employee_id, s.work_date, NULL, 'claude',
  GREATEST(0, COALESCE(s.claude_messages, 0) - COALESCE(t.m, 0)),
  GREATEST(0, COALESCE(s.claude_tokens, 0) - COALESCE(t.tok, 0)),
  GREATEST(0, COALESCE(s.claude_cache_read, 0) - COALESCE(t.cr, 0)),
  GREATEST(0, COALESCE(s.claude_cache_creation, 0) - COALESCE(t.cc, 0)),
  GREATEST(0, COALESCE(s.claude_cost_usd, 0) - COALESCE(t.cost, 0)),
  s.computed_at
FROM daily_summary s
LEFT JOIN (
  SELECT employee_id, work_date,
    SUM(COALESCE(claude_messages, 0)) m, SUM(COALESCE(claude_tokens, 0)) tok,
    SUM(COALESCE(claude_cache_read, 0)) cr, SUM(COALESCE(claude_cache_creation, 0)) cc,
    SUM(COALESCE(claude_cost_usd, 0)) cost
  FROM daily_task_time GROUP BY employee_id, work_date
) t ON t.employee_id = s.employee_id AND t.work_date = s.work_date
WHERE COALESCE(s.claude_messages, 0) > COALESCE(t.m, 0)
   OR COALESCE(s.claude_tokens, 0) > COALESCE(t.tok, 0)
   OR COALESCE(s.claude_cache_read, 0) > COALESCE(t.cr, 0)
   OR COALESCE(s.claude_cache_creation, 0) > COALESCE(t.cc, 0)
   OR COALESCE(s.claude_cost_usd, 0) > COALESCE(t.cost, 0) + 1e-9;
ALTER TABLE daily_summary DROP COLUMN claude_messages;
ALTER TABLE daily_summary DROP COLUMN claude_tokens;
ALTER TABLE daily_summary DROP COLUMN claude_cache_read;
ALTER TABLE daily_summary DROP COLUMN claude_cache_creation;
ALTER TABLE daily_summary DROP COLUMN claude_cost_usd;
ALTER TABLE daily_task_time DROP COLUMN claude_messages;
ALTER TABLE daily_task_time DROP COLUMN claude_tokens;
ALTER TABLE daily_task_time DROP COLUMN claude_cache_read;
ALTER TABLE daily_task_time DROP COLUMN claude_cache_creation;
ALTER TABLE daily_task_time DROP COLUMN claude_cost_usd;
"""

# v4 (E9.1, plane_exit): зеркало SQLite-v4 — нейтральные имена вместо plane_*.
_V4 = """
ALTER TABLE plane_transition RENAME TO task_transition;
ALTER TABLE task RENAME COLUMN plane_identifier TO identifier;
ALTER TABLE task RENAME COLUMN plane_issue_id TO external_uid;
ALTER TABLE project RENAME COLUMN plane_identifier TO identifier_prefix;
ALTER TABLE project DROP COLUMN plane_project_id;
"""

# v5 (спека 11, misc_works) — зеркало SQLite-v5: справочник спринтов + task.sprint_ext_id.
_V5 = f"""
CREATE TABLE sprint (
  id         {_ID},
  project_id INTEGER NOT NULL REFERENCES project(id),
  ext_id     TEXT NOT NULL,
  name       TEXT,
  ord        INTEGER,
  status     TEXT,
  start_date TEXT,
  end_date   TEXT,
  UNIQUE(project_id, ext_id)
);
ALTER TABLE task ADD COLUMN sprint_ext_id TEXT;
"""

# v6 (спека 12, E11 tg_assistant): выделенная схема обмена «бот-конспектор ↔ кабинет» — 4 таблицы
# СТРОГО по DDL §2 контракта TGA-26 (tg_chat_assistant/01_specs/02_tga26_cabinet_contract_spec.md).
# Единственное согласованное отступление от черновика контракта (спека 12 §3, решение 6.2):
# tg_chat_bindings.project_slug — NULLABLE (контракт давал NOT NULL). Привязка чата = заполнение
# slug; непривязанный чат = NULL → раздел «Чаты» кабинета показывает «неприсвоенные», unbind =
# project_slug=NULL. NULLABLE — надмножество NOT NULL: запись бота (всегда со slug) не ломается;
# бот-сторона уведомляется в issue #1 (TIME-71), чтобы научиться слать непривязанные чаты.
#
# ВАЖНО (отличия от миграций v1–v5):
#  • IF NOT EXISTS везде: схема tg_assistant — ГЛОБАЛЬНАЯ (создаётся вне search_path), а PG-тест
#    гоняет миграции в search_path=timechecker_test → один физический tg_assistant обслуживает два
#    леджера schema_migrations; без IF NOT EXISTS второй прогон упадёт (ревью плана #3).
#  • Роль бота tg_assistant_bot и гранты — НЕ в миграции (отдельный CLI `setup-bot-role`):
#    _executescript режет скрипт по «;», role-DDL и условные блоки этого не переживут (ревью #2).
#  • tg_journal.id — bigserial (как в контракте): создаёт sequence tg_journal_id_seq, на который
#    роли бота выдаётся USAGE,SELECT — иначе INSERT упадёт на nextval (ревью #1).
# В этом скрипте НЕТ «;» внутри литералов/блоков — _executescript режет по «;» корректно.
_V6 = """
CREATE SCHEMA IF NOT EXISTS tg_assistant;
CREATE TABLE IF NOT EXISTS tg_assistant.tg_chat_bindings (
  chat_id      bigint PRIMARY KEY,
  project_slug text,
  chat_title   text NOT NULL DEFAULT '',
  bound_via    text NOT NULL CHECK (bound_via IN ('cabinet','bot')),
  active       boolean NOT NULL DEFAULT true,
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS tg_assistant.tg_digests (
  project_slug text NOT NULL,
  date         date NOT NULL,
  content_md   text NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (project_slug, date)
);
CREATE TABLE IF NOT EXISTS tg_assistant.tg_topics (
  project_slug text NOT NULL,
  name         text NOT NULL,
  content_md   text NOT NULL,
  updated_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (project_slug, name)
);
CREATE TABLE IF NOT EXISTS tg_assistant.tg_journal (
  id           bigserial PRIMARY KEY,
  project_slug text NOT NULL,
  kind         text NOT NULL CHECK (kind IN ('decision','wish')),
  date         date NOT NULL,
  text         text NOT NULL,
  norm_text    text NOT NULL,
  UNIQUE (project_slug, kind, norm_text)
);
"""

MIGRATIONS: list[tuple[int, str]] = [
    (1, _V1),
    (2, _V2),
    (3, _V3),
    (4, _V4),
    (5, _V5),
    (6, _V6),
]
